language: python
matrix:
  include:
  - env: CACHE_NAME=8.0 DEPLOY_DOC_FROM_BRANCH=master DEPLOY_DOC_TO_DIRECTORY=doc/html SAGE_SERVER=http://mirrors.xmission.com/sage/ SAGE_IMAGE=linux/64bit/sage-8.0-Ubuntu_14.04-x86_64.tar.bz2
    dist: trusty
  - env: CACHE_NAME=7.6 SAGE_SERVER=http://mirrors.xmission.com/sage/ SAGE_IMAGE=linux/64bit/sage-7.6-Ubuntu_12.04-x86_64.tar.bz2
    dist: precise
  - env: CACHE_NAME=7.5.1 SAGE_SERVER=http://mirrors.xmission.com/sage/ SAGE_IMAGE=linux/64bit/sage-7.5.1-Ubuntu_12.04-x86_64.tar.bz2
    dist: precise
install:
- ./.travis-install.sh
script:
- ./.travis-test.sh
cache:
  directories:
  - $HOME/SageMath
  - $HOME/.cache/matplotlib
  timeout: 1000
before_cache:
- rm -Rf $HOME/SageMath/logs $HOME/SageMath/.BUILDSTART
after_success:
- ./.travis-deploy-doc.sh
before_script:
- openssl aes-256-cbc -K $encrypted_71e928c0b1a9_key -iv $encrypted_71e928c0b1a9_iv
  -in .travis_ci_gh_pages_deploy_key.enc -out .travis_ci_gh_pages_deploy_key -d

addons:
  apt:
    packages:
     # On 8.0 with trusty, Fortran compiler is needed, or optional package install will decide to build gcc.
     - gfortran
