language: python

env:
  - CACHE_NAME=7.1 SAGE_SERVER=http://mirrors.xmission.com/sage/ SAGE_IMAGE=linux/64bit/sage-7.1-Ubuntu_12.04-x86_64.tar.bz2
  - CACHE_NAME=7.2 SAGE_SERVER=http://mirrors.xmission.com/sage/ SAGE_IMAGE=linux/64bit/sage-7.2-Ubuntu_12.04-x86_64.tar.bz2
  - CACHE_NAME=7.3 SAGE_SERVER=http://mirrors.xmission.com/sage/ SAGE_IMAGE=linux/64bit/sage-7.3-Ubuntu_12.04-x86_64.tar.bz2
  - CACHE_NAME=7.4 SAGE_SERVER=http://mirrors.xmission.com/sage/ SAGE_IMAGE=linux/64bit/sage-7.4-Ubuntu_12.04-x86_64.tar.bz2

matrix:
  allow_failures:
  - env: CACHE_NAME=7.1 SAGE_SERVER=http://mirrors.xmission.com/sage/ SAGE_IMAGE=linux/64bit/sage-7.1-Ubuntu_12.04-x86_64.tar.bz2

install:
  - ./.travis-install.sh

script:
  - ./.travis-test.sh

cache:
  directories:
    - $HOME/SageMath
    - $HOME/.cache/matplotlib
  timeout: 1000

before_cache:
 - rm -Rf $HOME/SageMath/logs $HOME/SageMath/.BUILDSTART
