## This is a conda environment file.
## See https://towardsdatascience.com/a-guide-to-conda-environments-bc6180fc533
## or    https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html
name: sage-cgf
channels:
  - conda-forge
  - defaults
dependencies:
  - sage=8.8
  - sphinxcontrib-websupport
  - sphinxcontrib-bibtex
  - lrslib
  - normaliz
  - pip
